### PR TITLE
Resource badges

### PR DESCRIPTION
**Pull request by Estecka**
This is module allows drawing every resource's icon using RoomVisuals.
I originally shared it on [screep's forum](https://screeps.com/forum/topic/2469), and was suggested to share it here as well.

### CODE REVIEW

**Comment by AlinaNova21** [comment]
Looks great! I would say go ahead and combine it into the roomvisual.js file, mostly so that its just a single file for users to drop in and require rather than two.

**Comment by AlinaNova21** [comment]
If you could add the image to the PR and README, that would be nice too. I still haven't done that yet with the rest of it :(

**Comment by Estecka** [comment]
It's done.  
Though I believe it's for the best to keep what can be separated into separate modules; it lets users cherry-pick the features they want, and helps preventing unrelated codes from conflicting with each other. (Here for example, I had a `const Color` while there already was a `const colors`.

**Comment by AlinaNova21** [comment]
May be worth adding a simple build setup with them split, that way the user has a choice between pulling in the individual smaller modules, or one combined one.

**Pull request merged**
